#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rclone"
name = "Rclone"
description.en = "Web UI for Rclone"
description.fr = "Interface utilisateur Web pour Rclone"

version = "1.74.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://rclone.org/"
userdoc = "https://rclone.org/docs/"
code = "https://github.com/rclone/rclone"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/rclone"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/rclone/rclone/releases/download/v1.74.2/rclone-v1.74.2-linux-amd64.zip"
    amd64.sha256 = "72a806370072015ccbe4d81bcd348cc5eaf3beca6c65ba693fd43fb31fcca5b1"
    arm64.url = "https://github.com/rclone/rclone/releases/download/v1.74.2/rclone-v1.74.2-linux-arm64.zip"
    arm64.sha256 = "bc2b2eb8269b743ed7bcea869f3782cfb4931e41efa53fc8befc6dc8308b7a50"
    armhf.url = "https://github.com/rclone/rclone/releases/download/v1.74.2/rclone-v1.74.2-linux-arm.zip"
    armhf.sha256 = "ec8cc4e0b94c61453f8aebf68b13073189fe0beb53aacf1a88f0e702d3c510cf"
    i386.url = "https://github.com/rclone/rclone/releases/download/v1.74.2/rclone-v1.74.2-linux-386.zip"
    i386.sha256 = "a74e8b3f31ae32cd888767cf518ec922b0478dd933c297701dd56c8cd389e657"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*-linux-amd64.zip"
    autoupdate.asset.arm64 = ".*-linux-arm64.zip"
    autoupdate.asset.i386 = ".*-linux-386.zip"
    autoupdate.asset.armhf = ".*-linux-arm.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
     main.default = 5572
