#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rclone"
name = "Rclone"
description.en = "Web UI for Rclone"
description.fr = "Interface utilisateur Web pour Rclone"

version = "1.74.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://rclone.org/"
userdoc = "https://rclone.org/docs/"
code = "https://github.com/rclone/rclone"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/rclone"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/rclone/rclone/releases/download/v1.74.0/rclone-v1.74.0-linux-amd64.zip"
    amd64.sha256 = "61de0a78d8776fe3e080f8385ebe96d817f2ee6a6003fe36b2d9f3b49d3e36ea"
    arm64.url = "https://github.com/rclone/rclone/releases/download/v1.74.0/rclone-v1.74.0-linux-arm64.zip"
    arm64.sha256 = "c28148f72e82e16953a9f7eedbe610736968240318ff33872f90bfdd689cc72f"
    armhf.url = "https://github.com/rclone/rclone/releases/download/v1.74.0/rclone-v1.74.0-linux-arm.zip"
    armhf.sha256 = "679473a02c9f50f8c365a8e703ea29d30e454c1a628c90792234fb1580998b48"
    i386.url = "https://github.com/rclone/rclone/releases/download/v1.74.0/rclone-v1.74.0-linux-386.zip"
    i386.sha256 = "98672c590c9055a4a64fd02d49a548abdb905f13aa34679b7aeda983ee2240d0"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*-linux-amd64.zip"
    autoupdate.asset.arm64 = ".*-linux-arm64.zip"
    autoupdate.asset.i386 = ".*-linux-386.zip"
    autoupdate.asset.armhf = ".*-linux-arm.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
     main.default = 5572
