#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rclone"
name = "Rclone"
description.en = "Web UI for Rclone"
description.fr = "Interface utilisateur Web pour Rclone"

version = "1.75.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://rclone.org/"
userdoc = "https://rclone.org/docs/"
code = "https://github.com/rclone/rclone"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/rclone"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/rclone/rclone/releases/download/v1.75.0/rclone-v1.75.0-linux-amd64.zip"
    amd64.sha256 = "aa2804e08f48250e71009c727124b6341cd0288465804a9a09d14663cabafbaa"
    arm64.url = "https://github.com/rclone/rclone/releases/download/v1.75.0/rclone-v1.75.0-linux-arm64.zip"
    arm64.sha256 = "d0ad88ba4c8e285b7c9efa591e0ab643280a91741e13c27f3a9c0957ccfa5203"
    armhf.url = "https://github.com/rclone/rclone/releases/download/v1.75.0/rclone-v1.75.0-linux-arm.zip"
    armhf.sha256 = "17f3f07cfa17e065f0c3329149ba702bbaafdb87e7f00230830488d5391362f2"
    i386.url = "https://github.com/rclone/rclone/releases/download/v1.75.0/rclone-v1.75.0-linux-386.zip"
    i386.sha256 = "0cd6d0a18cf50004851e23f97dbcad5ebd16047590a704daebfbfe402425aefe"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*-linux-amd64.zip"
    autoupdate.asset.arm64 = ".*-linux-arm64.zip"
    autoupdate.asset.i386 = ".*-linux-386.zip"
    autoupdate.asset.armhf = ".*-linux-arm.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
     main.default = 5572
